on: 
  workflow_dispatch: 
  pull_request: {}
  push:
    branches:
    - main
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 05 5 * * 1
name: Semgrep
jobs:
  buildGradleLockFiles:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build Dependency Tree
        run: gradlew --init-script enable-locking.init.gradle.kts writeLocksForScan --write-locks --no-daemon
      - name: Create Zip File
        run: find . -type f -name 'gradle.lockfile' -exec zip -r archive.zip {} +
      - name: Upload Dependency Zip
        uses: actions/upload-artifact@v3
        with:
          name: zipfile
          path: archive.zip
  semgrep:
    needs: buildGradleLockFiles
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      SEMGREP_REPO_DISPLAY_NAME: gsecops/gradle-kotlin-spring/lockfilecommitted
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact from the previous job
        uses: actions/download-artifact@v3
        with:
          name: zipfile
      - name: Semgrep Scan
        run: |
          unzip -o archive.zip
          semgrep ci --supply-chain
